# Generated by Django 5.2.4 on 2025-07-10 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa sauny')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Pojemność (osoby)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za godzinę')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Sauna',
                'verbose_name_plural': 'Sauny',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Czas zakończenia')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Całkowita cena')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na płatność'), ('paid', 'Opłacona'), ('cancelled', 'Anulowana'), ('completed', 'Zrealizowana')], default='pending', max_length=20, verbose_name='Status rezerwacji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID płatności (Przelewy24)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('sauna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.sauna', verbose_name='Sauna')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['start_time'],
                'unique_together': {('sauna', 'start_time', 'end_time')},
            },
        ),
    ]
